name: CI

on:
  push:
    branches: [ main ]
    tags: [ v*.*.* ]

  pull_request:
    branches: [ main ]
    types:
      - synchronize
      - opened
      - reopened

jobs:
  call_ci:
    uses: EffectiveRange/ci-workflows/.github/workflows/python-ci.yaml@latest-python
    with:
      package-type: 'wheel'
      coverage-threshold: 85
      test-distribution: 'trixie'
      package-architecture: '["amd64"]'

  dispatch_downstream:
    if: startsWith(github.ref, 'refs/tags/')
    name: Dispatch downstream repo
    needs: call_ci
    uses: EffectiveRange/ci-workflows/.github/workflows/repository-dispatch.yaml@v1_repodispatch
    secrets: inherit
    with:
      downstream_repo: devc-effectiverange-baseoverlay
      event_type: ${{ github.repository }}
      version: ${{ github.ref_name }}    